### ISSUE TITLE
Replace % with ! and place operators after type names

### ISSUE THREAD

**Issue by PhilipWitte** [andrewrk/zig#121]
Zig looks like it's well designed in many ways, and overall the syntax is clean and readable. That said, IMO the `%` operator is ugly, and the operator placement for it and `?` doesn't feel right being in front of type names. Instead, I would propose using the `!` operator for error unions, and moving both it and `?` to after type names. This would make it common to see types like `u8?` and `u8!?` throughout Zig code, which is both amusing (as it looks kinda like the type is surprised or swearing), and closer to written English (which would probably make code more natural to read & write for many people). Example:

```zig
fn do_something() -> u8!?
{
    if (some_condition()) {
        return malloc(1) ?? null;
    } else {
        return error.SomeError;
    }
}
```

**Comment by thejoshwolfe** [comment]
what do you think about `&` coming before types for pointers? like `&u8` instead of `u8&`.

**Comment by andrewrk** [comment]
You almost certainly would not have an error union wrapped in a maybe type. You would instead introduce another error value:

```zig
error OutOfMem;
fn do_something() -> %u8 {
    if (some_condition()) {
        return malloc(1) ?? error.OutOfMem;
    } else {
        return error.SomeError;
    }
}
```

As for putting the operators after instead of before, consider that all pointers imported from C .h files are maybe pointers. So, if you import a C prototype that looks like this:

```c
void get_pointer_to_thing(struct Foo **thing);
```

In Zig this prototype looks like this:

```zig
extern fn get_pointer_to_thing(thing: ?&?&Foo);
```

What would it look like with your proposal?

**Comment by thejoshwolfe** [comment]
I agree that `?` and `!` being postfix operators is more natural, because that's how they're used in english (and it's how `?` is used in C#). It raises some interesting readability issues though, like what type is this: `&u8?`? Is it maybe a pointer to `u8`? or is it a pointer to a maybe `u8`? Whereas if they're all prefix operators, then `?&u8` vs `&?u8` is easy to distinguish. Also, you can read types out loud from left to right with prefix operators: `&?u8` is a "pointer to maybe u8".

If we make all three type modifiers postfix operators, then there's no ambiguity either. `u8?&` is definitely a pointer to a maybe `u8`. You read the type from right to left this time, which probably isn't too much to ask.

However, there's a parsing problem with postfix operators that can also be infix operators. Consider this code `foo??(bar)`. If `?` is a postfix operator and `??` is an infix operator, the expression is technically ambiguous. We could interpret it as the type `foo??` being invoked as a function: `((foo?)?)(bar)`, or we could interpret it as `foo` defaulting to `(bar)`: `foo ?? bar`. This problems could be worked around with various strategies, but this is inherently more difficult to parse, both for machines and for humans, than the unambiguous prefix notation currently in place.

Regarding `!` meaning errors instead of `%`, yeah that would be way better. That was originally the plan. However, we need a prefix operator as discussed above, and `!` was already taken as a prefix operator for bool inversion--the "not" operator. We considered moving the "not" operator to a different symbol, but thought that would be too foreign to programmers familiar with the very well established `!` meaning.

**Comment by PhilipWitte** [comment]
@andrewrk Okay, I've only quickly read through your introduction about Zig, and was under the impression that `%` and `?` would be commonly used together.. I still don't know why you're saying it would be very uncommon, as functions returning a 'maybe' are about more than just allocating memory, but also about referencing some other part of the program under some specific runtime condition (where returning 'null' would not be an 'error', but rather a indication of state).. But I'm not very familiar with writing software without null, and even less familiar with Zig, so likely this is just my ignorance showing through.

As for how how that C function would look in my proposal, I imagine it would look almost identical to how you've written it, only with the `?&?&` after the type. That said, if those two symbols (I'm assuming `&` refers to the const-state the underlying pointer) are more commonly used together, then perhaps it would be better to replace `&` with `!` instead, and keep the error handling operator close-to, or the same as your current design (eg, `?&u8` -> `u8!?`, `%?u8` -> `%u8?` or `#u8?`... idk, I just don't like the `%` symbol for some reason, but of course that's entirely subjective).

**Comment by PhilipWitte** [comment]
@thejoshwolfe That's a good point about `foo??` and `foo ?? bar`` being ambiguous.. Did not consider that.

**Comment by andrewrk** [comment]
There's also the `!=` operator. If `!` means error, then what would the boolean inequality operator be?

**Comment by PhilipWitte** [comment]
@andrewrk That's a good point, and since `!=` is a commonly understood operator I certainly wouldn't recommend changing it.
