### ISSUE TITLE
add hex literal, binary literal, float literal, hex float literal

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#15]
* [x] hex literal
 * [x] binary literal
 * [ ] float literal (support decimal and E notation)
 * [x] hex float literal
 * [x] octal literal

**Comment by thejoshwolfe** [comment]
here's a test for trying out hex float literals

```
#include <stdio.h>
#include <stdint.h>

int main() {
    float f = 0x1f.0fp-4f;
    uint32_t bits = *(int *)&f;
    for (int i = 31; i >= 0; i--) {
        if (i == 30 || i == 22) printf(" ");
        printf("%d", (bits >> i) & 1);
    }
    printf("\n");
    return 0;
}
```

```
$ gcc -std=c99 -Wall -Werror -Wpedantic a.c && ./a.out && rm a.out 
0 01111111 11110000111100000000000
```

**Comment by thejoshwolfe** [comment]
```
[<radix>]<whole_number>[.<fraction>][<exponent_designtator>[<sign>]<exponent>]
```

`radix` can be `0x` for hex, `0o` for octal, or `0b` for binary. In hex, the digits `a-f` are case insensitive.

if either the `fraction` or `exponent` are given, then it is a float literal. otherwise, it's an integer literal.

the `whole_number` and the `fraction` are interpreted in the radix specified. the `exponent` is always specified in base 10.

`exponent_designator` is `e` or `E` for base 2, 8, and 10, and `p` or `P` for base 16.

`sign` is `+` or `-`.

the significance of the exponent is `10^exp` for base 10 floats and `2^exp` for base 2, 8, and 16 floats. This means that `0x1p4` is `0x10` not `0x10000`.

This is very similar to the C99 syntax. It is more flexible in these ways:

 * octal literals start with `0o` instead of just `0`.
 * binary literals exist.
 * octal and binary float literals exist.
 * the exponent is not required for hex float literals.

I don't know about compliance with the IEEE 754-2008 standard; I can't find a copy of it on the internet.
