### ISSUE TITLE
Proposal: remove multiline comments

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#161]
Status quo:

Multiline comments start with `/*` and end with `*/`, and they nest. The name "multiline" is a bit misleading, because in fact, these style of comments have power that single line comments do not have, which is ability to insert in the middle of an expression:

```zig
const sum = a + /* comment */ b;
```

Removing multiline comments would remove this ability.

Rationale:

Modern text editors make it easy to insert some characters in front of many lines at once; commenting out a block of code by prefixing each line with `//` should be easy.

One of the points of contention in C is whether to use `/* */` or `//` for comments. Only having one way to do things is one of Zig's goals.

This sidesteps the question of whether multiline comments should nest or not.

**Comment by thejoshwolfe** [comment]
Removing `/* */` comments has another minor benefit, which is a step toward enabling editors to understand the middle of a large source file without scanning the entire document to find out whether or not we're in a comment or not. This goal might be a lost cause though, since string literals can still cause this exact problem.

I'm generally in favor of removing `/* */` comments, since i prefer to use `//` comments myself, and i don't like that my preference has competition. :)

**Comment by kiljacken** [comment]
While not a big deal with this exact feature, be careful not to go full APL "because editors can do better" :)

**Comment by andrewrk** [comment]
@kiljacken can you elaborate? I know you're slightly kidding but I'm taking your warning seriously.

**Comment by kiljacken** [comment]
Well, the story with APL is that it's reached a point of using abstract symbols for operations "because editors/keyboard can do better". It's reached a point (or well, have been at it for many many years) where you cannot feasibly code APL without a special keyboard or an editor specially tuned for APL.

That said, APL and Zig are very far apart from both syntactic and semantic standpoints, so the extent to which this can go bad in Zig seems rather limited.

As an aside, here is an example APL program, the one generating the first `R` prime numbers:
```
(~R∊R∘.×R)/R←1↓ιR
```
Beautifully dense, and quite expressive (if you know the symbols), but fairly impractical in your plain vim/emacs/nano/etc. :)

**Comment by thejoshwolfe** [comment]
I think we're all pretty much in agreement here, but just to follow up, the editor features we're designing for with this proposal are the rectangle select and rectangle edit modes that many general-purpose code editors already have today. Some editors are even more specialized with a feature for toggling comments (e.g. Ctrl+/ in eclipse JDT and CDT), but we're not designing for that kind of thing. We're not asking editors to design for us; we're designing for existing editors.

**Comment by thejoshwolfe** [comment]
> This goal might be a lost cause though, since string literals can still cause this exact problem.

This is not true anymore. See #162.

Now every newline character in a .zig source file resets the tokenizer state, so a syntax highlighter can always be correct on a line-aligned excerpt of code.

**Comment by PavelVozenilek** [comment]
Embedded `/* ... */`  comments have good use in C, as the language does not support named parameters:
  `foo(1 /* this */, 2 /* that */, 3 /* ... */);`
or inside complicated expressions.

There are people who prefer to provide documentation in form of very detailed comments (for example Doug Lea's allocator http://gee.cs.oswego.edu/pub/misc/malloc-2.7.0.c ) and the language should not fight them.

**Comment by marler8997** [comment]
Could support embedded comments another way,
```
foo(1 // this */);
// or
foo(1 // this //);
// or
foo(1 // this /);
```

**Comment by andrewrk** [comment]
You can still do that by using new lines and it arguably even looks better. There's also a proposal discussed on IRC for named parameters at the callsite. I'm not sure if that proposal has made its way to GitHub yet.

**Comment by rdbo** [comment]
I feel like this should be brought up again.

Advantages of "multiline" comments:
- Easy to use on any editor, including old software and constrained environments: commenting 50 lines by hand using `//` on apps like Notepad and `vi` would not be a fun task. I like and I do use modern editors, but I don't want to depend on them to get a job done
- Ability to do midline comments: Although I generally prefer to avoid them, they have a few use cases - `const a = 1337 /* special number for something */;` or like mentioned above, `foo(1 /* this */, 2 /* that */, 3 /* ... */);`
- Less overall file size: this doesn't matter much since we have a ton of storage these days, but the amount of bytes it takes to comment `N` lines with `/* */` is always `4`, whereas with `//` it is `N * 2`. So 1000 lines would be `2000` bytes, versus `4` using multiline comments.
- The multiline comment can do everything that the regular comment can: one could argue that perhaps you could keep multiline comments and remove single line comments, since the multiline comments are more powerful (I'm not necessarily in favor of that either, but it's something that could be brought up, since there should only be one way of doing things).

Disadvantages:
- Non-standard documentation: there seems to be an established pattern for documentation, using combinations like `///` and `//!`. This could be achieved with multiline comments, but it's not standardized.
- Slower parsing: it's easier to parse `//` than `/* */`, as pointed out in a discussion with other users. Is it worth killing a powerful feature like this though?

I don't think multiline comments are that big of a deal, but I'll sure remember that if I am in a constrained environment, or if I need to use some specific editor. Otherwise, I'll just keep using my regular editor and comment using its features. It would be nice to still have them though.

**Comment by GrauBlitz** [comment]
+1 for the comment above me

I just got into the language and was a bit shocked to see that there are no mulitline comments, if you don't want to use them fine, but why completely remove something very established, often used and implemented in almost every other programming language?

**Comment by a-y-u-s-h** [comment]
Personally, I don't mind if Zig supports multiline or single line comments, but I do mind how `///` and `//` look in the codebase - they feel unattractive to me. So I'm here to comment (just as a food for thought) my two cents - I feel like `#` for single line comments would look aesthetically pleasing (like Bash and other languages) and for multiline, I support this - `/* */`. 

Also, Is it too late to change this feature?

**Comment by 1vanK** [comment]
> +1 for the comment above me
> 
> I just got into the language and was a bit shocked to see that there are no mulitline comments, if you don't want to use them fine, but why completely remove something very established, often used and implemented in almost every other programming language?

This is where I finished my acquaintance with the language)) The author simply cannot be trusted. Suddenly at some point he wants the indentation to be exactly 5 spaces, otherwise the code will not compile.

**Comment by mlugg** [comment]
Attacks and strawman arguments against the language creator are not productive. If you have something to contribute, please do so; otherwise, you need not comment on issues such as this one.

This part of the language is fairly decided, and rehashing old arguments certainly won't change anything. Still, if you have a genuinely new point as to why you believe this design choice should be reconsidered, please share it.

I will quickly note here that a more usual way of "commenting out" code in Zig is to wrap it in `if (false)` - due to comptime evaluation rules, this is largely akin to `#if 0` in C. This removes in my experience the single biggest use case for multiline comments in other languages.

**Comment by GrauBlitz** [comment]
> I will quickly note here that a more usual way of "commenting out" code in Zig is to wrap it in `if (false)` - due to comptime evaluation rules, this is largely akin to `#if 0` in C. This removes in my experience the single biggest use case for multiline comments in other languages.

This is not only about code, this is also about normal comments and documentation. Despite this as many people said, why remove something well established, that does no harm? Also just writing /* and */ where I wont is a bit less cumbersome then writing some defines/if conditions, I never used something like `#if 0 #endif` in my C code, why would I, I can just use `/* */`...

**Comment by nektro** [comment]
> why remove something well established, that does no harm?

there are a handful of reasons why this decision was made and stays to this day but one of our [Community](https://github.com/ziglang/zig/wiki/Community)s is the place to ask those questions. (btw it's mostly performance at various levels)

**Comment by GrauBlitz** [comment]
> > why remove something well established, that does no harm?
> 
> there are a handful of reasons why this decision was made and stays to this day but one of our [Community](https://github.com/ziglang/zig/wiki/Community)s is the place to ask those questions. (btw it's mostly performance at various levels)

Thanks for the hint, but I decided to switch to Go instead, I just want to use a ready language that supports industry common practices and put that much time into discussing basic things like this.

**Comment by Des-Nerger** [comment]
Ok, I understand that Zig has removed the traditional kind of block comments like `/* ... */` in order to have `the property that each line of code can be tokenized out of context`. But. If the big text I want to comment out is _syntactically_ correct Zig code, why couldn't there be a directive to at least discard its AST after been parsed?
```zig
const std = @import("std");
const _ = @comment(
    pub fn thisFunctionIsCommentedOut() !void {
        const stdout = std.io.getStdOut().writer();
        try stdout.print("Hello, {s}!\n", .{"world"});
    }
);
```

**Comment by 418Cat** [comment]
Multiline comments have been a thing for a long time and are still industry standard in most new languages.
Zig not having multiline comments is an inconvenience that can and will bother some people. Not wanting to use them is fine, leaving the choice for that simple feature is better.

The fact that modern editors have the ability to comment many lines at the same time should not exempt zig from supporting multiline comments, also because they are more bounded comments than multiline.

**Comment by RetroDev256** [comment]
Aside from the arguments already made in this channel, I would like to add my perspective. I don't expect zig to change on this stance with multiline commenting, but add two new points:

1) Zig's frontend currently tokenizes an entire file from start to finish, so adding multiline comments should not significantly increase runtime or complexity of the compiler.

2) I recently heard an argument that multiline comments are "useful to comment out lots of code without a huge git diff". Also solved with a `if (!debugging) { ... }` block, writing the statement without greyed-out highlighting support in editors makes working with this method of debugging more tricky, not to mention more error-prone if you have a hard time matching opening and closing curly brackets.

**Comment by chillinbythetree** [comment]
Not having multiline comments is a joke.

**Comment by amarakon** [comment]
I know this has been changed a long time ago, but I urge the Zig developers to consider adding multiline comments back. My reasoning is simple: In my opinion, they significantly improve code readability when documenting functions. Above my functions, I like to put a single comment that’s two or three lines long that explains what the function does. When I’m forced to put `//` in front of each line, to me my brain reads it as three separate comments. Compare these two examples:

```c
// The formulas for calculating the battery remaining time are as follows:
//     - time to empty (discharging) = energy_now / power_now
//     - time to full (charging) = (energy_full - energy_now) / power_now
```

```c
/* The formulas for calculating the battery remaining time are as follows:
 *     - time to empty (discharging) = energy_now / power_now
 *     - time to full (charging) = (energy_full - energy_now) / power_now */
```

To me, the second one looks a lot less noisy. I think Zig has gone too far in enforcing ‘only one way to do things.’ Everyone has their own style for how they do functions, comments, indentation, etc. Imagine if we made it so that the opening brace of a function must start on the next line.
