### ISSUE TITLE
Proposal: Elm-inspired commenting

### ISSUE THREAD

**Issue by ajimu** [andrewrk/zig#178]
It's common for a programmer to (during writing, editing, and debugging) comment multiple groups of lines to observe behavior while looking at the previous behavior or write a function incrementally, especially during the process of learning a new language. [Elm is the best I've seen so far at facilitating this](http://elm-lang.org/docs/syntax#comments).

Further, I'd argue that comments serve two purposes: the "de-activating" of code, and in-source documentation. Both single-line and multi-line comments serve the former purpose, in different ways.

I've seen #161, so I'm not trying to demand anything or create any sense of obligation, but I would be remiss not to suggest that 'comments' be contemplated somewhat seriously as a feature that would affect the quality of experience using the language.

Thanks for reading

**Comment by andrewrk** [comment]
We have single line comments which serve all the purposes you mentioned above, deactivating code and providing in source documentation.

#161 explains the decision to remove multiline comments. In order to re-open this issue, please address the points made in that issue and provide an explanation of why the conclusion should be overturned.
