### ISSUE TITLE
unreachable syntax

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#214]
Status quo:

`unreachable` is a type. `@unreachable()` is control flow.

Proposal:

`unreachable` should be control flow, because all control flow happens with keywords. `if`, `switch`, `goto`, `return`, `while`, `for`.

Then the question becomes, how do we refer to the unreachable type? `@typeOf(unreachable)` should probably work. It's a bit awkward though, and do we want that in compile error messages?

Another proposal for the type: `Unreachable`. Maybe all primitive types would be capitalized, to adhere to the style conventions? `I32`, `U64`, `CDouble`, `Void`. I think I prefer the lower case primitive types though. That would make `Unreachable` stand out in a weird way.

**Comment by SirCmpwn** [comment]
Proposal: replace unreachable with assertions.

`assert(expr)` behaves like `expr` but if `expr` is falsey it (on debug) bitches about it and (on release) is undefined. Evaluated at compile time if possible. Perhaps with a special syntax for doing it at compile time versus runtime if necessary.

**Comment by SirCmpwn** [comment]
(and then assert(false) replaces unreachable)

**Comment by andrewrk** [comment]
`assert` is currently defined like this:

```zig
pub fn assert(ok: condition) {
    if (!ok) @unreachable();
}
```

This seems to me like the unreachable control flow - which is currently referred to with a builtin function - is the more fundamental control structure the language can give.

Another example, `%return foo` is equivalent to `foo %% @unreachable()`.

I agree that `assert(false)` and `@unreachable()` are equivalent, but it seems to me that the former is  naturally built on top of the latter.

> Evaluated at compile time if possible. Perhaps with a special syntax for doing it at compile time versus runtime if necessary.

Here are some possibilities:

 * Ability to annotate a function (such as `assert`) such that if the arguments to it are compile-time known, zig should evaluate that function at compile time.
 * Automatically detect when it is possible to do this, and do it.

You can already do `comptime assert(foo);` to force it to run at compile-time at the callsite.

**Comment by SirCmpwn** [comment]
unreachable just seems like such a weird idea. To me it doesn't follow at all that assert is naturally built on unreachable. Assert is easier to digest.

**Comment by andrewrk** [comment]
@thejoshwolfe what do you think about the primitive type being called `noreturn` and the control flow keyword being called `unreachable`?

```zig
fn abort() -> noreturn {
    // ...
}
fn assert(ok: bool) {
    if (!ok) unreachable;
}
```

**Comment by thejoshwolfe** [comment]
I like `noreturn`, because I believe the return types for functions is almost the only place you'll ever see that name.

Other places it would show up is if you're asking for the type of expressions that cause a jump in control flow, like `@typeOf(break)`. So ironically, `@typeOf(return)` would be `noreturn`; that's about as silly as JavaScript's `typeof NaN === 'number'`.

But I still think it's a good idea. `noreturn` is more clear than `unreachable` in a function signature. This would also make `unreachable` be a special statement, like `break` and `continue`, which seems like a good idea.

One idea, that I don't like, is renaming `@unreachable()` to indicate what's actually going to happen when control flow gets there. So when implementing `assert()`, it make say `@panic()` or something. However, the other usecase for `unreachable` is when you're documenting to the compiler and to other readers that it's impossible for control flow to get to a certain spot.

```zig
pthread_destroy(pthread_self());
unreachable;
```

We could put `@panic()` there, but if we did that, we'd probably also want a comment saying `// unreachable`, so I think the keyword should be just say "unreachable".

It might be kinda confusing for `assert()` to use `unreachable` in a panic situation, but I think it's actually the right thing to do. In no-safety mode, it's a claim that the conditions that would make assertions fail are impossible. In debug/safety mode, it's a hook to attach the debugger or print a stacktrace or whatever. We don't want the implementation of `assert()` to say `panic()`, because we actually don't want the no-safety mode to panic; we want to claim that it will never happen. The confusion comes from the perspective of a developer in debug mode where the `unreachable` statement doesn't say what will happen, and debug mode is probably where developers will be when they're learning Zig.

I think what I would vote for is do what @andrewrk suggests with `noreturn` as a type and `unreachable` as a control flow statement (or rather expression), and then put a comment in `assert()` explaining what `unreachable` will do when safety is enabled. The `unreachable` in `assert()` will be the `unreachable` that is most commonly violated by far, and usually in debug mode when "unreachable" is probably wrong, taken literally, so a comment would help explain what it means and even why it's called that.
