### ISSUE TITLE
Unable to initialize pointer to constant

### ISSUE THREAD

**Issue by SirCmpwn** [andrewrk/zig#227]
```
pub fn main(args: [][]u8) -> %void {
    var vga_mem: []u16 = (&u16)(0xB8000);
}
```

```
~/s/zig > zig build hello.zig --name hello --export exe
./hello.zig:2:33: error: integer value 753664 cannot be implicitly casted to type '&u16'
    var vga_mem: []u16 = (&u16)(0xB8000);
                                ^
```

This sort of thing is useful for doing memory mapped I/O.

**Comment by thejoshwolfe** [comment]
This seems like it should work. Do you have to cast it to usize first? like `(&u16)(usize(0xB8000))`? I don't think you should have to, unless we're really trying to discourage low level programming.

**Comment by SirCmpwn** [comment]
Cast to usize also segfaults.

**Comment by andrewrk** [comment]
I'm about to fix this. Sounds like you're going to need #238 soon after this.

**Comment by andrewrk** [comment]
```zig
pub fn main(args: [][]u8) -> %void {
    const vga_mem = (&u16)(usize(0xB8000));
}
```

This code compiles and works as expected for me. How are you getting it to segfault?

If you're talking about this:

```zig
pub fn main(args: [][]u8) -> %void {
    const vga_mem: []u16 = (&u16)(usize(0xB8000));
}
```

```
./test.zig:2:34: error: expected type '[]u16', found '&u16'
    const vga_mem: []u16 = (&u16)(usize(0xB8000));
                                 ^
```

The type `[]u16` is a slice, which has a pointer and a length; so you can't cast a pointer to a slice because you would be missing the length component. What you can do, however, is slice a pointer, giving it a length. So, how many `u16` values are in vga_mem? 100? Then you could do:

```
    const vga_mem: []u16 = (&u16)(usize(0xB8000))[0...100];
```

Anyway I'll add the ability to explicitly cast an integer literal to a pointer.

**Comment by SirCmpwn** [comment]
Thanks!
