### ISSUE TITLE
Infer return type when possible

### ISSUE THREAD

**Issue by SirCmpwn** [andrewrk/zig#230]
Before:

```
fn example(a: i32, b: i32) -> i32 {
    a + b
}
```

After:

```
fn example(a: i32, b: i32) {
    a + b
}
```

**Comment by thejoshwolfe** [comment]
I don't like this idea. I think documenting the return types of functions by explicitly writing the type improves readability. Obviously, there's a trade off between how much effort you require of code writers vs how much benefit you give to code readers, but I think function signatures is where we need to be explicit with types, both parameter types and return types. When a reader asks "what type is this?", they shouldn't have to look at more than 1 function signature for the answer.

Consider how many steps the programmer would need to take to determine the type of `foo` in the following example:

```zig
fn main() {
    var foo = f();
}
fn f() { g() }
fn g() { h() }
fn h() { true }
```

That being said, you actually can have the compiler figure out what the return type of a function should be, but the syntax is much *more* complicated than explicitly specifying the return type. I think this is good because it discourages programmers from omitting the type out of laziness. Calculating the return type should only be done when you have to, such as some situations with parameterized types, i.e. "template functions".

**Comment by SirCmpwn** [comment]
It's better to infer where possible and save time. You can solve the problem of figuring out what type a function is with editor tools.

**Comment by andrewrk** [comment]
It sounds like you are making an argument that the code writer's time is more important than the reader's time. Zig has generally sided thus far with the reader's time being more important.

**Comment by SirCmpwn** [comment]
Well, fair enough.
