### ISSUE TITLE
Proposal: delete typedefs

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#314]
The use cases for typedefs are:

```
type Meters = f64;
type Feet = f64;
const a: Meters = 10;
const b: feet = 13;
const c = a + b; // error: incompatible types
```

```
type c_style_void = u8;
fn doSomething(opaque: &c_style_void) {

}
```

The first use case can be solved by wrapping the thing in a struct. Second use case can be solved with public/private fields.

**Comment by raulgrell** [comment]
By wrapping it in a struct do you mean

```
const Meters = struct {
    value: f32
}
```
This feels like unecessary nesting.
```
type Feet = f64;

const Distance = enum {
    meters: Meters,
    feet: Feet,
}

const d = Distance.meters { Meters { .value = 1.0 } };
// vs
const e = Distance.feet { 1.0 }
```

**Comment by raulgrell** [comment]
I also don't understand what you mean in the second case, could you explain further or show an example of a solution?

**Comment by andrewrk** [comment]
That's a reasonable argument about unnecessary nesting. On the other hand you could make a shortcut function:

```zig
fn meters(value: f64) -> Distance {
    Distance.meters { Meters { .value = value, } }
}

const d = meters(1.0);
```

Also, if you have this enum that's really all you need to distinguish:

```zig
const Distance = enum {
    Meters: f64,
    Feet: f64,
};
const d = Distance.Meters { 1.0 };
```

In the second case, for example:

```zig
const MyThing = struct {
    // private fields
    a: i32,
    b: i32,

    pub fn init() -> MyThing {
        return MyThing { .a = 1, .b = 2, };
    }
    pub fn doSomething(self: &MyThing) {
    }
}
```

There is one more thing, that I neglected to mention, that we use typedefs for, and that is when we do a C import and we see something like:

```c
struct Foo;
void do_something(struct Foo *foo);
struct Bar;
void do_something_bar(struct Bar *bar);
```

We need `Foo` to now represent an opaque type that can't accidentally be passed to `do_something_bar`.

We also need a way to represent this type in zig even if we don't parse a C import.

However the way we use typedefs for this is suboptimal. Currently we do:

```zig
type Foo = u8;
```

The problem with this is that the underlying type of `Foo` is not actually `u8`, it is opaque. So this typedef lets you do something like `foo += 1` which should be a compile error.

So this proposal would be to delete typedefs and then introduce a way to create a truly opaque type.

**Comment by thejoshwolfe** [comment]
Zig doesn't actually have private fields; it just has fields, right?

I agree with getting rid of the awful Feet vs Meters nonsense. I have a long rant prepared about how putting units of measurement into the type system of a programming language is too hard to be worth while, but i won't dump that here (unless someone asks).

The ability to create opaque types seems valuable, especially for expressing C header concepts in Zig. How about:

```zig
const Foo = @OpaqueType();
fn do_something(foo: &Foo) {}
```

Another usecase for typedefs that haven't been discussed yet is creating variations on existing types that have different attributes. For example, making a non-copyable version of a struct. I can try to think of a more fleshed out example, but I'm actually in favor of removing typedefs instead of trying to come up with a problem to fit the solution. I don't think the existing usecases for typedefs are very valuable.

**Comment by andrewrk** [comment]
> Zig doesn't actually have private fields; it just has fields, right?

Status quo is we parse the word `pub` in front of fields, but then do nothing with the information, and there are no compile errors for accessing private fields.
